version: 0.2
phases:
  install:
    commands:
       - echo Installing source NPM dependencies...
       - npm install
       - npm install -g @angular/cli
  pre_build:
    commands:
      - npm test
      - rm -rf node_modules
  build:
    commands:
       - echo Build started on `date`
       - ng build --prod --aot

artifacts:
  files:
    - '**/*'
