    version: 0.2
    
 env:
    variables:
        BUILD_ENV : "prod"
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
      - rm -rf node_modules
  build:
    commands:
      - npm install --${BUILD_ENV} 
      - npm run build

artifacts:
  files:
    - '**/*'
